### ISSUE TITLE
Handle iterable callables [Memory.getByte() strange return]

### ISSUE THREAD

**Issue by gitshirokai** [justfoxing/ghidra_bridge#27]
Hello,

Im trying ghidra_bridge for the first time.

I would like to read a byte from memory with :

```
function = getFunctionContaining(address)
body = function.getBody()
addr = body.getMinAddress()
b = ghidra.program.model.mem.Memory.getByte(addr)
```

This following error is raised

```
AssertionError: Found something callable and iterable at the same time
```

This is strange because its only a byte ...

thank you for your answer :)

**Comment by justfoxing** [comment]
Cool! I left that assert in to try and pick up cases of dual-callable and iterable objects. Having a look, it looks like this is actually being caused by trying to reference the ghidra.program.model.mem.Memory class - it's not actually executing the getByte method.

So, on the plus side, thanks for the test case - I'll use that to work out how I should handle iterable callables, and hopefully fix it when I get round to the next update.

Even better news for you though - your code snippet isn't actually how to get a byte (ghidra.program.model.mem.Memory is an interface that isn't meant to be referenced directly). You need to get an object that implements the Memory interface - `currentProgram.getMemory()` is probably the easiest. Try your snippet as:
```
function = getFunctionContaining(address)
body = function.getBody()
addr = body.getMinAddress()
b = currentProgram.getMemory().getByte(addr)
```
Hope that gets you going again!

**Comment by justfoxing** [comment]
Decided the easiest way to handle the case of Jython classes with the __iter__ function (like ghidra.program.model.mem.Memory) is to special case them (they'll just be BridgedCallables). Leaving the assert in place to detect other instances of __iter__ + callable, and I'll come up with a better solution then if required.
