### ISSUE TITLE
[Errno 111]Connection refused

### ISSUE THREAD

**Issue by jpc0016** [justfoxing/ghidra_bridge#31]
Good morning,

While running the ghidra_bridge_server.py script, I executed the setup client code in step 2 and received a connection refused socket.error.  I used an example binary file with a valid entry point address and installed ghidra_bridge using pip.  Any idea what a socket error could stem from?

**Comment by fmagin** [comment]
Have you waited until the log message in Ghidra bridge says that it is up and running? The bridge takes a bit to setup and if you try connecting before the socket won't be open yet.
Is there any other log message in the Ghidra log?

Otherwise try standard network troubleshooting, i.e.:
* is the port open? (check with `ss -tlpn` on Linux or the windows equivalent)
* can you reach from localhost (check with `nc` or similiar tools)
* do you have a firewall that might be blocking it (unlikely due to connection refused and not timeout)

**Comment by jpc0016** [comment]
Hi, does ghidra_bridge use a default port number?  This would help narrow down where the expected communication should happen.

**Comment by fmagin** [comment]
Should be 4768 as seen here https://github.com/justfoxing/ghidra_bridge/blob/master/ghidra_bridge/bridge.py#L43

**Comment by jpc0016** [comment]
Ok I found something weird.  Ghidra shows the below in the console.  Is 54228 the port number?

```
ghidra_bridge_server.py> Running...
INFO:ghidra_bridge.bridge:serving!
WARNING:ghidra_bridge.bridge:Handling connection from ('127.0.0.1', **54228**)
```

And port 4768 appears to be working:

```
LISTEN                           0                                 5                                                             [::ffff:127.0.0.1]:4768                                                                    *:* 
```

**Comment by fmagin** [comment]
54228 is the source port number.
Is that the address that port is open on?  `[::ffff:127.0.0.1]:4768` seems a bit weird, half IPv6 half IPv4. Maybe that is the issue.

**Comment by jpc0016** [comment]
I have no idea where 54228 is coming from.  It's not listed in my ss command.  The source code for bridge.py clearly states the default port is 4768.

**Comment by fmagin** [comment]
Yes, but TCP connections come from a host:port and connect to a host:port. In most cases the sourceport is irrelevant and just chosen randomly. If you run `ss` without the `-l` flag (for listening ports) it should appear. Did you manage to connect now, because _something_ seems to be connecting to your bridge. If you don't know what is connecting you can check with `ss -tnp` which should show one established connection to the port 4768 and from whatever the host:port in the log is.

**Comment by jpc0016** [comment]
Sorry for not posting earlier.  Here's the exact error I received from running the client Python script:

```
Traceback (most recent call last):
  File "test_ghidra.py", line 10, in <module>
    with ghidra_bridge.GhidraBridge(namespace=globals()):
  File "/usr/local/lib/python2.7/dist-packages/ghidra_bridge/ghidra_bridge.py", line 32, in __init__
    self.get_flat_api(namespace=self.namespace)
  File "/usr/local/lib/python2.7/dist-packages/ghidra_bridge/ghidra_bridge.py", line 42, in get_flat_api
    remote_main = self.bridge.remote_import("__main__")
  File "/usr/local/lib/python2.7/dist-packages/ghidra_bridge/bridge.py", line 542, in remote_import
    return self.client.remote_import(module_name)
  File "/usr/local/lib/python2.7/dist-packages/ghidra_bridge/bridge.py", line 428, in remote_import
    return self.deserialize_from_dict(self.send_cmd(command_dict))
  File "/usr/local/lib/python2.7/dist-packages/ghidra_bridge/bridge.py", line 326, in send_cmd
    sock = self.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/ghidra_bridge/bridge.py", line 312, in get_socket
    self.sock.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
```

**Comment by fmagin** [comment]
That doesn't say more than the connection got refused.
You said you got the message:
```
ghidra_bridge_server.py> Running...
INFO:ghidra_bridge.bridge:serving!
WARNING:ghidra_bridge.bridge:Handling connection from ('127.0.0.1', **54228**)
```

Do you get that without initiating a connection from the ghidra_bridge client? _Something_ seems to be connection, and it can't really be your client because that is getting a connection refused.

**Comment by justfoxing** [comment]
This issue has gone a bit stale, and I've released a few major updates since then. If you still experience problems with the latest version of ghidra_bridge (0.2.0), hit me up and we'll go from there
