### ISSUE TITLE
PyPI description has three sequential steps all numbered "1"

### ISSUE THREAD

**Issue by gtackett** [justfoxing/ghidra_bridge#54]
At the PyPI website, the description for the Ghidra Bridge project has three sequential installation steps that are all numbered "1".

Perhaps the description there hasn't been updated from the latest readme.md on github?

"A picture is worth a thousand words", so:
![Capto_Capture 2020-12-03_11-21-45_AM](https://user-images.githubusercontent.com/52077/101057243-d6616280-3559-11eb-84fe-c4db49d5f15b.png)

**Comment by justfoxing** [comment]
The README's up to date - other details from the latest release are present. The issue is Pypi's markdown parser behaving differently from Github's - I've explicitly numbered those steps in the README, but Pypi's markdown parser is ignoring that. 

Thanks for the report, I'll take a quick attempt to fix it whenever I next do a release, but IMO the intent of the section is still clear and I'm not going to spend too much time trying to work around competing parser implementations.

**Comment by gtackett** [comment]
I understand that it’s a very minor issue. Just wanted to let you know.
