### ISSUE TITLE
setComment causes BridgeException

### ISSUE THREAD

**Issue by raw-data** [justfoxing/ghidra_bridge#61]
Hi @justfoxing! 

I am currently testing `ghidra_bridge` with
- Python 3.8.5
- Ghidra 10.0.2

and while trying to set a comment I get the below error

```
BridgeException: ('Transaction has not been started', <_bridged_db.NoTransactionException('db.NoTransactionException: Transaction has not been started', type=db.NoTransactionException .....)>)
```

The code I am executing is the following
```
currentProgram.getListing().getCodeUnitAt(toAddr("<ADD-HERE-ADDR>")).setComment(0, "Just a comment!")
# setComment(0, "Just a comment!")  is the same as 
# setComment(ghidra.program.model.listing.CodeUnit.EOL_COMMENT, "Just a comment!")
# but also with this, it does not work
```
Can you suggest a workaround to this issue? Thank you!

**Comment by justfoxing** [comment]
Hey, this is an easy one - the BridgeException is wrapping the real exception from Ghidra, which is a NoTransactionException, so this isn't to do with ghidra_bridge at all (you'd get the same result if you did this in Ghidra's built-in python).

NoTransactionException happens because Ghidra wants you to start a "transaction" before doing anything that alters the state of the database underlying the RE (such as adding a comment). You're not the first person to hit this - see https://github.com/justfoxing/ghidra_bridge/issues/56#issuecomment-770312736 for a quick example of how to solve this.

**Comment by raw-data** [comment]
@justfoxing indeed your suggestion fixed it ... before posting the issue yesterday, I checked within Ghidra and setting the comment (like in my previous post) worked, but it could also be that, once the Ghidra env is loaded, the API call to `start()` happens in the background (?) , anyhow, thank you!
