### ISSUE TITLE
How to remote debug with VSCode?

### ISSUE THREAD

**Issue by blacktop** [justfoxing/ghidra_bridge#68]
Is there a host/port I can use?

**Comment by justfoxing** [comment]
Unclear what you're trying to do.

If you're debugging the client side, it'll just be a python process you can
use standard python debugging tools with.

If you're trying to debug the bridge server running in ghidra, that's going
to be way harder - because of the complexity (python code running in a Java
process), I mostly just add logging messages to inspect what's going on.

If what you're trying to debug isn't related to ghidra itself, but the
behaviour of the bridge, you can just use the underlying jfx-bridge project
to run the bridge server in its own python process, and again debug that
with standard python tools.

I'll leave it up to you to figure out how best to integrate that advice
into your own preferred IDE setup.

**Comment by blacktop** [comment]
yeah I have a 
```py
b = ghidra_bridge.GhidraBridge(
    namespace=globals(),
    hook_import=True,
    response_timeout=20,
)  # creates the bridge and loads the flat API into the global namespace
print(getState().getCurrentAddress().getOffset())
# ghidra module implicitly loaded at the same time as the flat API
ghidra.program.model.data.DataUtilities.isUndefinedData(currentProgram, currentAddress)
```
and them some ghidra imports and ghidra API calls and wanted to step debug, but in VSCode the "Step" button doesn't do anything, I assume what I want is instead pydevd? Seems super gross though because I have to somehow enable it in Ghdira via eclipse?

**Comment by justfoxing** [comment]
Oh, right, so you want to debug the effects of a script you're running
through ghidra-bridge on the ghidra side. Yeah, integration with debuggers
is not a feature we support.

My recommendation would be to remove ghidra-bridge from the debugging
problem - try to pull out the part of your script that you're interested in
into a python or java script that you can run directly in ghidra, then use
ghidra's recommendations for debugging that without the added complexity of
the bridge.

**Comment by blacktop** [comment]
😞 👍
