### ISSUE TITLE
How to pass arguments to the post script 

### ISSUE THREAD

**Issue by fourat-bs** [justfoxing/ghidra_bridge#71]
Hello @justfoxing,

I want to spawn multiple python subprocesses to analyze different files at the same time. The command I use is the following :
```bash
$ghidraRoot/support/analyzeHeadless.bat <path to directory to store project> <name for project> -import <path to file to import>  -scriptPath <install directory for the server scripts> -postscript ghidra_bridge_server.py
```
Each analysis require different port, so I tried to refactor the **`ghidra_bridge_server.py`** file to pass the host and port as arguments using `sys.argv` or `argparse` like this : 
```bash
$ghidraRoot/support/analyzeHeadless.bat <path to directory to store project> <name for project> -import <path to file to import>  -scriptPath <install directory for the server scripts> -postscript ghidra_bridge_server.py port host
```
PS: found in Ghidra docs that you can pass arguments to the post script.
But no luck.
Next I tried running the hole thing on a docker container for each analysis, but first I changed the **`ghidra_bridge_server.py`** to read host and port from ENV, resulted in networking issues and can't reach the bridge server.
ENV variables without docker are hard to implement because subshells will inherit the same env variables from the main shell.
Any hints/suggestions will be appreciated it.

**Comment by justfoxing** [comment]
So as you've spotted, there's no dynamic configuration for the server port. I'd be willing to look at a PR if you worked it up.

Some suggestions: 
* `GhidraBridgeServer.run_server(server_port=####)` is the function and argument you want to start the server listening on a specific port. Maybe instead of modifying ghidra_bridge_server.py, make a thin wrapper around it (see ghidra_bridge_server_background.py for an example of a wrapper) where you put the logic for pulling port details from argparse or env or whatever.
* If you're using docker, you shouldn't have to modify ghidra_bridge_server.py at all - just use the -p flag when you start the docker container to map the default ghidra server port in the container to something different on the host (e.g., `-p <new host port>:4768`). That's probably the easiest option in fact, once you sort out the networking for your specific environment.
* I'm assuming you're remembering to setup the ghidra_bridge client with the new server port when you connect (`GhidraBridge(connect_to_port=####)`), but just try using netcat or something that's not ghidra_bridge to connect to the new server port when you're testing and ensure that a TCP connection can at least establish, to rule out any issues from ghidra_bridge client

Good luck!
